export const productConstants = {
  GET_ALL_PORTFOLIOS_REQUEST: 'GET_ALL_PORTFOLIOS_REQUEST',
  GET_ALL_PORTFOLIOS_SUCCESS: 'GET_ALL_PORTFOLIOS_SUCCESS',
  GET_ALL_PORTFOLIOS_FAILURE: 'GET_ALL_PORTFOLIOS_FAILURE',
  SET_SELECTED_TAG: 'SET_SELECTED_TAG',
};
